<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ClientsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('clients')->delete();
        
        \DB::table('clients')->insert(array (
            0 => 
            array (
                'id' => 1,
                'client_name' => 'wipro',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => 3649,
                'state_id' => 26,
                'district_id' => 417,
                'created_at' => '2022-04-02 11:03:50',
                'updated_at' => '2022-04-02 11:03:50',
            ),
            1 => 
            array (
                'id' => 2,
                'client_name' => 'wipro',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => 3649,
                'state_id' => 26,
                'district_id' => 417,
                'created_at' => '2022-04-02 11:04:37',
                'updated_at' => '2022-04-02 11:04:37',
            ),
            2 => 
            array (
                'id' => 3,
                'client_name' => 'wipro',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => 3649,
                'state_id' => 26,
                'district_id' => 417,
                'created_at' => '2022-04-02 11:06:55',
                'updated_at' => '2022-04-02 11:06:55',
            ),
            3 => 
            array (
                'id' => 4,
                'client_name' => 'wipro',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => 3649,
                'state_id' => 26,
                'district_id' => 417,
                'created_at' => '2022-04-02 11:14:52',
                'updated_at' => '2022-04-02 11:14:52',
            ),
            4 => 
            array (
                'id' => 5,
                'client_name' => 'wipro',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 26,
                'district_id' => NULL,
                'created_at' => '2022-04-02 11:16:40',
                'updated_at' => '2022-04-02 11:16:40',
            ),
            5 => 
            array (
                'id' => 6,
                'client_name' => 'wipro',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 26,
                'district_id' => NULL,
                'created_at' => '2022-04-02 11:21:05',
                'updated_at' => '2022-04-02 11:21:05',
            ),
            6 => 
            array (
                'id' => 7,
                'client_name' => 'wipro',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 26,
                'district_id' => NULL,
                'created_at' => '2022-04-02 11:22:27',
                'updated_at' => '2022-04-02 11:22:27',
            ),
            7 => 
            array (
                'id' => 8,
                'client_name' => 'wipro',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 26,
                'district_id' => NULL,
                'created_at' => '2022-04-02 11:22:45',
                'updated_at' => '2022-04-02 11:22:45',
            ),
            8 => 
            array (
                'id' => 9,
                'client_name' => 'wipro',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 26,
                'district_id' => NULL,
                'created_at' => '2022-04-02 11:23:08',
                'updated_at' => '2022-04-02 11:23:08',
            ),
            9 => 
            array (
                'id' => 10,
                'client_name' => 'wipro',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 26,
                'district_id' => NULL,
                'created_at' => '2022-04-02 11:24:16',
                'updated_at' => '2022-04-02 11:24:16',
            ),
            10 => 
            array (
                'id' => 11,
                'client_name' => 'wiproooooooooooaaaa',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 2,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => 2788,
                'state_id' => 4,
                'district_id' => 337,
                'created_at' => '2022-04-02 11:39:37',
                'updated_at' => '2022-04-02 11:39:37',
            ),
            11 => 
            array (
                'id' => 12,
                'client_name' => 'wiproooooooooooaaaa',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 2,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => 2788,
                'state_id' => 4,
                'district_id' => 337,
                'created_at' => '2022-04-02 12:13:06',
                'updated_at' => '2022-04-02 12:13:06',
            ),
            12 => 
            array (
                'id' => 13,
                'client_name' => 'wiproooooooooooaaaa',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 2,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => 2788,
                'state_id' => 4,
                'district_id' => 337,
                'created_at' => '2022-04-02 12:20:26',
                'updated_at' => '2022-04-02 12:20:26',
            ),
            13 => 
            array (
                'id' => 14,
                'client_name' => 'wiproooooooooooaaaa',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 2,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => 2788,
                'state_id' => 4,
                'district_id' => 337,
                'created_at' => '2022-04-02 12:20:44',
                'updated_at' => '2022-04-02 12:20:44',
            ),
            14 => 
            array (
                'id' => 15,
                'client_name' => 'wiproooooooooooaaaa',
                'mobile' => '7766889901',
                'email' => NULL,
                'door_no' => '305',
                'street_name' => 'bbsr',
                'pincode' => '755039',
                'area_name' => 'bbsr',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 2,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => 2788,
                'state_id' => 4,
                'district_id' => 337,
                'created_at' => '2022-04-02 12:22:14',
                'updated_at' => '2022-04-02 12:22:14',
            ),
            15 => 
            array (
                'id' => 16,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:24:12',
                'updated_at' => '2022-04-02 12:24:12',
            ),
            16 => 
            array (
                'id' => 17,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:25:12',
                'updated_at' => '2022-04-02 12:25:12',
            ),
            17 => 
            array (
                'id' => 18,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:25:48',
                'updated_at' => '2022-04-02 12:25:48',
            ),
            18 => 
            array (
                'id' => 19,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:26:03',
                'updated_at' => '2022-04-02 12:26:03',
            ),
            19 => 
            array (
                'id' => 20,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:26:49',
                'updated_at' => '2022-04-02 12:26:49',
            ),
            20 => 
            array (
                'id' => 21,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:27:28',
                'updated_at' => '2022-04-02 12:27:28',
            ),
            21 => 
            array (
                'id' => 22,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:27:34',
                'updated_at' => '2022-04-02 12:27:34',
            ),
            22 => 
            array (
                'id' => 23,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:27:45',
                'updated_at' => '2022-04-02 12:27:45',
            ),
            23 => 
            array (
                'id' => 24,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:28:21',
                'updated_at' => '2022-04-02 12:28:21',
            ),
            24 => 
            array (
                'id' => 25,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:28:32',
                'updated_at' => '2022-04-02 12:28:32',
            ),
            25 => 
            array (
                'id' => 26,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:29:27',
                'updated_at' => '2022-04-02 12:29:27',
            ),
            26 => 
            array (
                'id' => 27,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:29:36',
                'updated_at' => '2022-04-02 12:29:36',
            ),
            27 => 
            array (
                'id' => 28,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:31:11',
                'updated_at' => '2022-04-02 12:31:11',
            ),
            28 => 
            array (
                'id' => 29,
                'client_name' => 'Xyla Melton',
                'mobile' => 'Ginger Bruce',
                'email' => NULL,
                'door_no' => 'Jena Whitney',
                'street_name' => 'Pamela Workman',
                'pincode' => 'Rhonda Copeland',
                'area_name' => 'Veniam perspiciatis',
                'is_approve' => 0,
                'approved_by' => NULL,
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'crm_id' => '1',
                'city_id' => NULL,
                'state_id' => 1,
                'district_id' => NULL,
                'created_at' => '2022-04-02 12:31:25',
                'updated_at' => '2022-04-02 12:31:25',
            ),
        ));
        
        
    }
}