<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ClientContactsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('client_contacts')->delete();
        
        \DB::table('client_contacts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'contact_name' => 'Hadassah Wiley',
                'client_id' => 12,
            'mobile' => '+1 (896) 156-4871',
                'email' => 'loxoho@mailinator.com',
            'designation' => '+1 (117) 174-6263',
                'password' => NULL,
            'door_no' => '+1 (862) 122-5613',
                'street_name' => 'Henry Hays',
            'pincode' => '+1 (228) 146-2383',
            'area_name' => '+1 (658) 535-9446',
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'city_id' => '2702',
                'state_id' => '3',
                'district_id' => '199',
                'created_at' => '2022-04-02 12:13:06',
                'updated_at' => '2022-04-02 12:13:06',
            ),
            1 => 
            array (
                'id' => 2,
                'contact_name' => 'Brynn Bass',
                'client_id' => 12,
            'mobile' => '+1 (577) 224-2999',
                'email' => 'kiveke@mailinator.com',
            'designation' => '+1 (782) 375-5062',
                'password' => NULL,
            'door_no' => '+1 (245) 433-9813',
                'street_name' => 'Frances Pierce',
            'pincode' => '+1 (683) 254-9013',
            'area_name' => '+1 (476) 353-6049',
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'city_id' => '2927',
                'state_id' => '15',
                'district_id' => '289',
                'created_at' => '2022-04-02 12:13:06',
                'updated_at' => '2022-04-02 12:13:06',
            ),
            2 => 
            array (
                'id' => 3,
                'contact_name' => 'Hadassah Wiley',
                'client_id' => 15,
            'mobile' => '+1 (896) 156-4871',
                'email' => 'loxoho@mailinator.com',
            'designation' => '+1 (117) 174-6263',
                'password' => NULL,
            'door_no' => '+1 (862) 122-5613',
                'street_name' => 'Henry Hays',
            'pincode' => '+1 (228) 146-2383',
            'area_name' => '+1 (658) 535-9446',
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'city_id' => '2702',
                'state_id' => '3',
                'district_id' => '199',
                'created_at' => '2022-04-02 12:22:14',
                'updated_at' => '2022-04-02 12:22:14',
            ),
            3 => 
            array (
                'id' => 4,
                'contact_name' => 'Brynn Bass',
                'client_id' => 15,
            'mobile' => '+1 (577) 224-2999',
                'email' => 'kiveke@mailinator.com',
            'designation' => '+1 (782) 375-5062',
                'password' => NULL,
            'door_no' => '+1 (245) 433-9813',
                'street_name' => 'Frances Pierce',
            'pincode' => '+1 (683) 254-9013',
            'area_name' => '+1 (476) 353-6049',
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'city_id' => '2927',
                'state_id' => '15',
                'district_id' => '289',
                'created_at' => '2022-04-02 12:22:14',
                'updated_at' => '2022-04-02 12:22:14',
            ),
            4 => 
            array (
                'id' => 5,
                'contact_name' => 'Stacy Sargent',
                'client_id' => 16,
            'mobile' => '+1 (891) 326-6003',
                'email' => 'tasej@mailinator.com',
            'designation' => '+1 (786) 176-4176',
                'password' => NULL,
            'door_no' => '+1 (499) 536-4668',
                'street_name' => 'Adele Frye',
            'pincode' => '+1 (716) 677-3667',
            'area_name' => '+1 (151) 621-8592',
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'city_id' => '4247',
                'state_id' => '16',
                'district_id' => '337',
                'created_at' => '2022-04-02 12:24:12',
                'updated_at' => '2022-04-02 12:24:12',
            ),
            5 => 
            array (
                'id' => 6,
                'contact_name' => 'Hayfa Moon',
                'client_id' => 29,
            'mobile' => '+1 (694) 468-1243',
                'email' => 'lalofom@mailinator.com',
            'designation' => '+1 (909) 452-8163',
                'password' => NULL,
            'door_no' => '+1 (134) 234-8622',
                'street_name' => 'Karly Molina',
            'pincode' => '+1 (194) 667-1116',
            'area_name' => '+1 (134) 493-9753',
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'city_id' => '2230',
                'state_id' => '32',
                'district_id' => '172',
                'created_at' => '2022-04-02 12:31:25',
                'updated_at' => '2022-04-02 12:31:25',
            ),
            6 => 
            array (
                'id' => 7,
                'contact_name' => 'Julie Kirkland',
                'client_id' => 29,
            'mobile' => '+1 (644) 293-2558',
                'email' => 'bopeqed@mailinator.com',
            'designation' => '+1 (199) 837-3184',
                'password' => NULL,
            'door_no' => '+1 (668) 899-9534',
                'street_name' => 'Nehru Vaughan',
            'pincode' => '+1 (697) 285-8659',
            'area_name' => '+1 (663) 302-2553',
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 2,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'city_id' => '3924',
                'state_id' => '15',
                'district_id' => '128',
                'created_at' => '2022-04-02 12:31:25',
                'updated_at' => '2022-04-02 12:31:25',
            ),
            7 => 
            array (
                'id' => 8,
                'contact_name' => 'Mollie Gibbs',
                'client_id' => 29,
            'mobile' => '+1 (282) 572-1553',
                'email' => 'vegin@mailinator.com',
            'designation' => '+1 (845) 813-4332',
                'password' => NULL,
            'door_no' => '+1 (649) 705-3312',
                'street_name' => 'Liberty Yang',
            'pincode' => '+1 (603) 278-8735',
            'area_name' => '+1 (703) 918-9622',
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'city_id' => '4547',
                'state_id' => '9',
                'district_id' => '553',
                'created_at' => '2022-04-02 12:31:25',
                'updated_at' => '2022-04-02 12:31:25',
            ),
            8 => 
            array (
                'id' => 9,
                'contact_name' => 'Leslie Nunez',
                'client_id' => 29,
            'mobile' => '+1 (198) 976-3308',
                'email' => 'conysyrul@mailinator.com',
            'designation' => '+1 (466) 734-3081',
                'password' => NULL,
            'door_no' => '+1 (883) 572-6768',
                'street_name' => 'Jenette Armstrong',
            'pincode' => '+1 (491) 322-4346',
            'area_name' => '+1 (356) 849-6726',
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 2,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'city_id' => '3286',
                'state_id' => '13',
                'district_id' => '562',
                'created_at' => '2022-04-02 12:31:25',
                'updated_at' => '2022-04-02 12:31:25',
            ),
            9 => 
            array (
                'id' => 10,
                'contact_name' => 'Deborah Callahan',
                'client_id' => 29,
            'mobile' => '+1 (113) 998-5489',
                'email' => 'pokumyhur@mailinator.com',
            'designation' => '+1 (629) 596-9445',
                'password' => NULL,
            'door_no' => '+1 (531) 465-2457',
                'street_name' => 'Dean Silva',
            'pincode' => '+1 (579) 106-5387',
            'area_name' => '+1 (164) 425-8631',
                'approve_date' => NULL,
                'remarks' => NULL,
                'address' => NULL,
                'is_inactive' => NULL,
                'status' => 1,
                'is_deleted' => 'Y',
                'modified_by' => NULL,
                'created_by' => NULL,
                'city_id' => '1633',
                'state_id' => '30',
                'district_id' => '207',
                'created_at' => '2022-04-02 12:31:25',
                'updated_at' => '2022-04-02 12:31:25',
            ),
        ));
        
        
    }
}